# Generated by Django 4.0.6 on 2022-08-23 20:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='no title', max_length=50)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2022, 8, 24, 1, 38, 51, 796513))),
                ('note_content', models.CharField(default='no Content', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_seq', models.IntegerField(default=0)),
                ('fname', models.CharField(default='no name', max_length=30)),
                ('lname', models.CharField(default='no name', max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('profile_img', models.ImageField(default='dp/blank-profile-picture.webp', upload_to='dp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
